language: objective-c
osx_image: xcode8.3
before_install:
    - chmod a+x ./.travis/install.sh
    - chmod a+x ./.travis/build.sh
install:
    - source ./.travis/install.sh
script:
    - source ./.travis/build.sh
